### ISSUE TITLE
最新版goland激活不了

### ISSUE THREAD

**Issue by bqf9979** [superbeyone/JetBrainsActiveCode#1]
提示许可证已经被注销

**Comment by bqf9979** [comment]
2019.3.1
![22](https://user-images.githubusercontent.com/24972164/71757362-37a72e80-2ed0-11ea-8af8-f154cb70d91f.jpg)

**Comment by Luo-XD** [comment]
同问

**Comment by superbeyone** [comment]
已更新，试试
