### ISSUE TITLE
This license UX394X3HLT has been suspended. Please contact your license administrator.

### ISSUE THREAD

**Issue by Sonic72kon** [superbeyone/JetBrainsActiveCode#10]
<img width="912" alt="Screenshot 2024-03-04 at 8 29 45 PM" src="https://github.com/superbeyone/JetBrainsActiveCode/assets/121505462/a5717879-6faf-4e34-8ac6-17ea44f72251">

**Comment by sleeping-in-bed** [comment]
`
import os
from pathlib import Path


ip_list = ['13.248.188.196', '76.223.63.197', '13.225.183.104', '13.225.183.60', '13.225.183.89', '13.225.183.35',
           '54.228.155.20', '99.81.82.192']
app_path_list = [r'C:\Program Files\JetBrains\PyCharm 2023.3.3\bin\pycharm64.exe',
                 r'C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.3\bin\idea64.exe']

for app_path in app_path_list:
    command = ('netsh advfirewall firewall add rule '
               f'name="{Path(app_path).stem}" dir=out action=block '
               f'program="{app_path}" remoteip={",".join(ip_list)}')
    print(command)
    os.system(command)
`
I wrote a python script on Windows to solve this problem, and other platforms can try similar ideas to add these ip to firewall rules

**Comment by Sonic72kon** [comment]
There is a temporary way to use jetbrains programs until the repository author posts a new activation code.

Set localhost in the proxy settings

<img width="565" alt="Screenshot 2024-03-04 at 8 50 47 PM" src="https://github.com/superbeyone/JetBrainsActiveCode/assets/121505462/1562a810-3d5e-4ea7-a477-665ebd309689">

The program will work but plugins that depend on the Internet are unlikely to be

**Comment by MineMine59** [comment]
不管用bro

**Comment by MineMine59** [comment]
> 不管用bro

管用了 sorry 爱你

**Comment by superbeyone** [comment]
done
